language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 19.0
  - 20.0
  - 21.0
  - 22.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.0
    - elixir: 1.9
      otp_release: 19.0
    - elixir: 1.10
      otp_release: 19.0
    - elixir: 1.10
      otp_release: 20.0

script:
  - mix format --check-formatted
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
